### ISSUE TITLE
Make a Kong authorization plugin based on Casbin

### ISSUE THREAD

**Issue by hsluoyz** [casbin-lua/kong-authz#1]
Kong is a very popular gateway in Lua: https://github.com/Kong/kong

They have a plugin system to support 3rd-party plugins. See some RBAC plugins:

1. https://github.com/prabago/kong-plugin-jwt-auth-rbac
2. https://github.com/danis24/kong-rbac
3. https://konghq.com/blog/authorize-api-opa-kuma

We also need to make a Casbin plugin for Kong, and finally put our repo into the official plugin list: https://docs.konghq.com/hub/

**Comment by hsluoyz** [comment]
@rushitote

**Comment by rushitote** [comment]
Thanks, I will start working on this in a day or so.

**Comment by hsluoyz** [comment]
Basically usable now.
