### ISSUE TITLE
Fix the CI error

### ISSUE THREAD

**Issue by hsluoyz** [casbin-lua/kong-authz#11]
https://github.com/casbin-lua/kong-authz/runs/7718648324?check_suite_focus=true

![image](https://user-images.githubusercontent.com/3787410/183338481-72f3a0d0-cb4b-45bc-9eba-df9980cf00b2.png)

**Comment by conghuhu** [comment]
# Description
[kong #7317](https://github.com/Kong/kong/discussions/7317)
This issue mentioned this issue, the reasons for summarizing：
In Postgres version 13, the default value is scram-sha-256.
But Kong does not supported scram-sha-256.


# Two solutions
 - The current better solution is to use postgres:9.6.
 - You need to modify your password_encryption setting in postgresql.conf file.You need to motify it from scram-sha-256 to md5.And restart your Postgres service.

In CI, I think we can use postgres:9.6.

**Comment by rushitote** [comment]
I think lowering the postgres version in the CI is a better solution.

**Comment by hsluoyz** [comment]
Agreed
