### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by chaitanya14** [casbin-lua/kong-authz#18]
Please add below line to the read me installation for linux users.

sudo apk add gcc pcre pcre-dev libc-dev

https://github.com/casbin/lua-casbin/issues/145

**Comment by hsluoyz** [comment]
@chaitanya14 can you make a PR to fix it?

**Comment by chaitanya14** [comment]
Sure! Let me do it.

**Comment by chaitanya14** [comment]
> Sure! Let me do it.

Done! https://github.com/casbin-lua/kong-authz/pull/19
