### ISSUE TITLE
Support to use Casbin policy from DB

### ISSUE THREAD

**Issue by hsluoyz** [casbin-lua/kong-authz#7]
Right now we only support CSV file: https://github.com/casbin-lua/kong-authz#configuration

Need to support DB like other languages.

We already have adapters like: https://github.com/casbin-lua?q=adapter&type=all&language=&sort=

![image](https://user-images.githubusercontent.com/3787410/182113895-c7ec0b9a-8900-4149-b22c-6b10fc294b5f.png)

The question is how to let this kong-authz plugin to use the above adapters to connect to DB

**Comment by conghuhu** [comment]
I want try.

**Comment by hsluoyz** [comment]
@conghuhu go ahead!
